site_name: Lemon
site_description: Documentation for Lemon.
site_author: Nova/mooncell07

theme:
  name: "material"
  logo: img/lemon.png
  favicon: img/lemon.ico
  palette:
    - scheme: slate
      primary: yellow
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

    - scheme: default
      primary: yellow
      toggle:
        icon: material/toggle-switch
        name: Switch to Dark mode

  features:
    - navigation.top

repo_name: mooncell07/Lemon
repo_url: https://github.com/mooncell07/Lemon

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
            how_root_heading: true
            members_order: "source"
        import:
            - https://docs.python.org/3.10/objects.inv

nav:
  - Home: index.md
  - Lemon.pie:
    - Lemon: Lemon.pie/lemon.md
    - Display: Lemon.pie/display.md
    - CPU: Lemon.pie/cpu.md
    - Memory: Lemon.pie/memory.md
    - Opcode: Lemon.pie/opcode.md
    - Keypad: Lemon.pie/keypad.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: "+"

extra_css:
- ./css/extra.css

copyright: Copyright 2023 - Present &copy; mooncell07
